### ISSUE TITLE
Support Google/Bionic's libc in addition to GNU's libc?

### ISSUE THREAD

**Issue by anonhostpi** [vpelletier/python-libaio#15]
This particular line calls on the glibc binary to provide support for sys/eventfd.h and bits/eventfs.h:

https://github.com/vpelletier/python-libaio/blob/5bdf8a50b24bcbe7aea610b5734d4cc1da0639f2/libaio/eventfd.py#L21

However, GNU's libc is not the only C lib for Linux. Another common C lib is Bionic's. It is primarily packaged with Android-based distros.

If GNU's libc is not present on the host, the above line errors out.

If this would be patched, the following platforms could be supported:
- Android
- Fire OS (Amazon's fork)
- One UI (Samsung's fork)
- EMUI (Huawei's fork)
- MIUI (Xaomi's fork)
- LineageOS
- GrapheneOS
- Kali NetHunter
- Anything from this list: https://en.wikipedia.org/wiki/List_of_custom_Android_distributions

**Comment by anonhostpi** [comment]
## Other Notes:

- _Differences between Bionic libc and C11/POSIX_: https://en.wikipedia.org/wiki/Bionic_(software)#Differences_from_POSIX
- _Google's eventfd_: https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/sys/eventfd.h

Also, from a code search, it is unclear what you intended to use eventfs for https://github.com/search?q=repo%3Avpelletier%2Fpython-libaio+eventf&type=code --however, this is coming _from someone who isn't a C programmer._ So, it may just not be obvious to me.

The core reason that Bionic's libc is used in Android rather than GNU's is the use of a BSD license instead of a LGPL. BSD licenses are less restrictive.

**Comment by anonhostpi** [comment]
Here is one method for checking the libc implementation:

### _libc_checker.sh_
`ld` is a common dynamic linker on Linux platforms (including Android). We can use it to determine where Python is pulling shared libraries from.
```bash
#!/bin/bash

# Get linker SEARCH_DIRs from `ld`
search_dirs=$(ld --verbose | grep SEARCH_DIR | awk -F'"' '{ for (i=2; i<=NF; i+=2) print $i }')
```
Then we can check the libc.so* files in these directories for the Bionic and GNU variants by using `strings`
```bash
#!/bin/bash

# Loop through each search directory
for dir in $search_dirs; do
    # Find libc.so* files in the directory
    libc_files=$(find "$dir" -type f -name "libc.so*" 2>/dev/null)
    
    # Check each libc file for "gnu" and "bionic" strings
    for libc_file in $libc_files; do
        echo "Checking $libc_file..."
        if strings "$libc_file" | grep -iq "bionic"; then
            echo "  Found 'bionic' string in $libc_file"
        elif strings "$libc_file" | grep -iq "gnu"; then
            echo "  Found 'gnu' string in $libc_file"
        else
            echo "  Neither 'gnu' nor 'bionic' found in $libc_file"
        fi
    done
done
```

Limitations:

This doesn't account for LD_LIBRARY_PATH, and it doesn't determine which of the files in those paths CDLL() will load, just what selection it can load from. Also ideally, this should be reimplemented in Python instead of Sh/Bash.

**Comment by vpelletier** [comment]
Thanks for this detailed bug report. Restricting this to the glibc was not intentional.

Seeing the `-name` predicate you chose, I believe 1438d184c3a836c5525b5229a694fd1d0e1dbd17 should hopefully fix this issue. Could you please check ?

About library lookup rules, I believe this is under ctypes' responsibility: it should (and likely does) just call the linker's functions, and from there the linker should apply the same rules as usual.

> Also, from a code search, it is unclear what you intended to use eventfs for https://github.com/search?q=repo%3Avpelletier%2Fpython-libaio+eventf&type=code --however, this is coming from someone who isn't a C programmer. So, it may just not be obvious to me.

The reason for `libaio/eventfd.py`'s existence, and by extension the `libaio.EventFD` class is that, simultaneously:
- `libaio` has [special support for `eventfd`-type files](https://github.com/vpelletier/python-libaio/blob/1438d184c3a836c5525b5229a694fd1d0e1dbd17/libaio/__init__.py#L162-L164), indicated per-aioblock using the `IOCB_FLAG_RESFD` flag documented in [io_submit(2)](https://www.man7.org/linux/man-pages/man2/io_submit.2.html), which allow bridging the gap with more traditional polling (select, poll, epoll, and most likely the other non-linux variants)
- the python library does not itself give access to `eventfd`
- the code needed to support it is very short, and did not seem worthy of living in its own separate package

**Comment by anonhostpi** [comment]
Got it. I was looking more specifically at the `eventfs` token that was in one of your comments. I couldn't see eventfs implemented anywhere. https://github.com/vpelletier/python-libaio/blob/master/libaio/eventfd.py#L17

> Minimal adaptation of sys/eventfd.h and **_bits/eventfs.h_**

**Comment by vpelletier** [comment]
Oh, that would be a typo. Fixed: 8f8542ff7a122137e071218e988b4fdb36571fb6

**Comment by anonhostpi** [comment]
> Seeing the `-name` predicate you chose, I believe [1438d18](https://github.com/vpelletier/python-libaio/commit/1438d184c3a836c5525b5229a694fd1d0e1dbd17) should hopefully fix this issue. Could you please check ?

LGTM (no errors on import anymore):

![image](https://github.com/vpelletier/python-libaio/assets/130698314/2df470d2-e85d-42d1-8f1f-c322970b8232)

**Comment by vpelletier** [comment]
Wonderful, I'll release this as 0.9.3 shortly.

**Comment by vpelletier** [comment]
Done: https://pypi.org/project/libaio/0.9.3/

Thank you very much.
