### ISSUE TITLE
The io in-kernel asynchronous I/O is equal to direct io?

### ISSUE THREAD

**Issue by pahome** [vpelletier/python-libaio#5]
In the readme.md, it said 

> This is about in-kernel, file-descriptor-based asynchronous I/O.

The async io in kernel is equal to direct io? or buffered io?

thx

**Comment by vpelletier** [comment]
AIO and direct/buffered IO are orthogonal.

AIO is about submitting IO tasks to the kernel, and being notified when they are complete.

Direct IO is about skipping kernel-level IO caching. This is useful when the application does its own caching, like mariadb/mysql. Buffered IO is the opposite: kernel-level IO caching is desired.

AIO can be done on cached or direct file descriptors, just as synchronous IO can be done on both. That line in the readme is because of pre-existing so-called "aio" libraries in python which are about [another approach to the eventloop](https://www.python.org/dev/peps/pep-3156/) and sadly share the name of this linux kernel mechanism although they work at completely different levels.

AIO could rather be likened to select/poll/epoll, although it goes one step further: instead of being notified that IO is possible (select/poll/epoll) and only then submitting a buffer to kernel (read/write/recv/sendto/...), with AIO the buffer is submitted to the kernel from the beginning, meaning that when the application is notified that IO is possible, that IO is already completed (modulo failure cases, of course). This reduces the number of back-and-forth between kernel space and user space, saving time.

For completeness, I implemented this to be able to access file descriptors which do not support any polling mechanism, only synchronous IO and AIO: functionfs, to implement USB device functions as a linux user space process.

**Comment by pahome** [comment]
Oh I got it, so the direct or not is determined by me.

Because you access the libaio library in kernel, that's why I need to submit memory-aligned buffer such as mmap, bytearray?

I apply this repo in python2.7 and it solves the problem which there's no aio library before python3

**Comment by vpelletier** [comment]
Direct or buffered can be controlled, typically it's the `O_DIRECT` flag for `open` (`os.open`, as these flags are not accessible via `file.__init__`), and maybe also via some ioctl/fcntl (manpages should tell). It's just completely independent from aio.

libaio is actually still in user space, and it basically only responsible for knowing which syscall to trigger for each operation (so a compiled library is perfect for this).

About python3, what library are you refering to ? I do not know of any python module (besides mine) which interfaces with linux kernel's aio - although the unfortunate name collision of the "asyncio" module does not help getting clear search results, even more so when it commonly gets abbreviated as "aio".

**Comment by pahome** [comment]
> About python3, what library are you refering to ? 

I mean there's no aio library in Python2.X. So I like the python-libaio repo. Thank you very much.
What's the difference between python-libaio and "asyncio"? The access pattern?

**Comment by vpelletier** [comment]
> What's the difference between python-libaio and "asyncio"? The access pattern?

To put it short: they have nothing in common, except the unfortunate naming collision (and I would blame python for not finding a more descriptive name, aio ~~in the linux kernel exists since around 2003~~ in POSIX is specified since 2001).

[asyncio PEP](https://www.python.org/dev/peps/pep-3156/)

[man 7 aio](http://man7.org/linux/man-pages/man7/aio.7.html) is what python-libaio is about.

**Comment by vpelletier** [comment]
Closing as direct vs. cached vs. aio has been cleared, but feel free to reopen if needed.

This issue actually made me go over libaio again and made me realise they added a feature. So I implemented it and made a release (0.3), plus a few improvements for next release.
